# MSVC configuration
spring.application.name=msvc-company
server.port=8009

# SpringDoc configurations
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/apidoc/swagger-ui.html
springdoc.api-docs.path=/apidoc/

# BD configuration using R2DBC (para SQL Server)
spring.r2dbc.url=r2dbc:sqlserver://localhost:8888;databaseName=CompanyDB
spring.r2dbc.username=sa
spring.r2dbc.password=yourpassword
spring.profiles.active=dev




# Modo Debug
debug=false